### ISSUE TITLE
Intersect lines and intersect line and circle throws python error

### ISSUE THREAD

**Issue by japeki** [GispoCoding/kimu#58]
When executing intersect lines or intersect line and circle following python error is logged (example for line and circle tool) and tool is not giving results:

2022-11-17T08:51:42     WARNING    Traceback (most recent call last):
              File "C:/Users/<user>/AppData/Roaming/QGIS/QGIS3\profiles\<user>/python/plugins\kimu\core\intersection_tool_line_circle.py", line 118, in canvasPressEvent
              line_coords = self._extract_points()
              File "C:/Users/<user>/AppData/Roaming/QGIS/QGIS3\profiles\<user>/python/plugins\kimu\core\intersection_tool_line_circle.py", line 306, in _extract_points
              if len(layer.selectedFeatures()) > 0:
             AttributeError: 'QgsRasterLayer' object has no attribute 'selectedFeatures'

Error doesn't happen If there isn't raster layers in the project.

**Comment by nmaarnio** [comment]
There is now a new release where this bug has been fixed @japeki . The release also has the circle as temporary feature -update. If there should occur any error, create an issue and I will take a look same or next day to get it quickly fixed.
